### ISSUE TITLE
roadmap: path to 1.0.0

### ISSUE THREAD

**Issue by talss89** [talss89/sprout#10]
This issue serves as a planning scratchpad to bring Sprout up to a stable 1.0.0 release.

### `<0.0.3`: For next pre-release

- [ ] feature: observability of snapshot sizes in stash and remote
- [ ] docs: installation, guides, reference docs
- [ ] feature: installers for linux, mac
- [ ] feature: env-var substitution in repo definitions

### `<1.0.0`: For stable

- [ ] test: integration test suite
- [ ] build: windows
- [ ] feature: installer for windows

### Backlog / Ideas(?)

- feature?: repo access token management
- feature?: share repo definitions
- feature?: punch-in for user passwords
- feature?: DB anonymisation
